Added support for precompiled headers of gcc 3.4.3.

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -463,7 +463,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE CC CFLAGS ac_ct_CC CCDEPMODE CPP LN_S build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL DYNAMIC_LD_LIBS WEFTS_CONFIG WEFTS_CXXFLAGS WEFTS_LIBS BINRELOC_CFLAGS BINRELOC_LIBS BINRELOC_TRUE BINRELOC_FALSE WIN32_TRUE WIN32_FALSE LIBOBJS CPPLIB LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE CC CFLAGS ac_ct_CC CCDEPMODE CPP LN_S build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL DYNAMIC_LD_LIBS WEFTS_CONFIG WEFTS_CXXFLAGS WEFTS_LIBS BINRELOC_CFLAGS BINRELOC_LIBS BINRELOC_TRUE BINRELOC_FALSE HAVE_PCH_TRUE HAVE_PCH_FALSE WIN32_TRUE WIN32_FALSE LIBOBJS CPPLIB LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1037,6 +1037,7 @@ Optional Features:
                           (default=enable when available)
   --enable-binreloc-threads      compile binary relocation with threads support
 	                         (default=yes)
+  --enable-pch            enables precompiled headers support
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -4383,7 +4384,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4386 "configure"' > conftest.$ac_ext
+  echo '#line 4387 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5275,7 +5276,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5278:" \
+echo "$as_me:5279:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6309,11 +6310,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6312: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6313: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6316: \$? = $ac_status" >&5
+   echo "$as_me:6317: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6542,11 +6543,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6545: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6546: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6549: \$? = $ac_status" >&5
+   echo "$as_me:6550: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6602,11 +6603,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6605: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6606: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6609: \$? = $ac_status" >&5
+   echo "$as_me:6610: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -7981,7 +7982,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*)
-    echo '#line 7984 "configure"' > conftest.$ac_ext
+    echo '#line 7985 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8841,7 +8842,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8844 "configure"
+#line 8845 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8939,7 +8940,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8942 "configure"
+#line 8943 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11118,11 +11119,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11121: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11122: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11125: \$? = $ac_status" >&5
+   echo "$as_me:11126: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -11178,11 +11179,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11181: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11182: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11185: \$? = $ac_status" >&5
+   echo "$as_me:11186: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11734,7 +11735,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*)
-    echo '#line 11737 "configure"' > conftest.$ac_ext
+    echo '#line 11738 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -12594,7 +12595,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12597 "configure"
+#line 12598 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12692,7 +12693,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12695 "configure"
+#line 12696 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13519,11 +13520,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13522: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13523: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13526: \$? = $ac_status" >&5
+   echo "$as_me:13527: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -13579,11 +13580,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13582: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13583: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13586: \$? = $ac_status" >&5
+   echo "$as_me:13587: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14938,7 +14939,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*)
-    echo '#line 14941 "configure"' > conftest.$ac_ext
+    echo '#line 14942 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -15668,11 +15669,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15671: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15672: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15675: \$? = $ac_status" >&5
+   echo "$as_me:15676: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15901,11 +15902,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15904: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15905: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15908: \$? = $ac_status" >&5
+   echo "$as_me:15909: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15961,11 +15962,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15964: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15965: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15968: \$? = $ac_status" >&5
+   echo "$as_me:15969: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17340,7 +17341,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*)
-    echo '#line 17343 "configure"' > conftest.$ac_ext
+    echo '#line 17344 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -18200,7 +18201,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18203 "configure"
+#line 18204 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18298,7 +18299,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18301 "configure"
+#line 18302 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -20037,6 +20038,42 @@ fi
 	fi
 
 
+	# Check whether --enable-pch or --disable-pch was given.
+if test "${enable_pch+set}" = set; then
+  enableval="$enable_pch"
+   use_pch=$enableval
+else
+   use_pch=no
+fi;
+
+	if test "$use_pch" = "yes"; then
+		echo "$as_me:$LINENO: checking whether $CXX supports precompiling c++ header files" >&5
+echo $ECHO_N "checking whether $CXX supports precompiling c++ header files... $ECHO_C" >&6
+		echo >conftest.h
+		if $CXX conftest.h >/dev/null 2>/dev/null; then
+			have_pch=yes
+		else
+			have_pch=no
+		fi
+		rm -f conftest.h conftest.h.gch
+		echo "$as_me:$LINENO: result: $have_pch" >&5
+echo "${ECHO_T}$have_pch" >&6
+	else
+		have_pch=no
+	fi
+
+
+
+if test "$have_pch" = "yes"; then
+  HAVE_PCH_TRUE=
+  HAVE_PCH_FALSE='#'
+else
+  HAVE_PCH_TRUE='#'
+  HAVE_PCH_FALSE=
+fi
+
+
+
 
 
 
@@ -20565,7 +20602,7 @@ done
 
 if test "$is_win" == "yes"; then
 	DEFS="$DEFS -DWIN32_LEAN_AND_MEAN"
-	CXXFLAGS="$CXXFLAGS -DWIN32_LEAN_AND_MEAN"
+	CPPFLAGS="$CPPFLAGS -DWIN32_LEAN_AND_MEAN"
 
 
 
@@ -23172,7 +23209,12 @@ else
 fi
 
 # Adding include dirs and WEFTS_ variables
-INCLUDES='-I$(top_srcdir)/libhypnos/ -I$(top_srcdir)/includes/'
+INCLUDES='-I$(top_builddir) -I$(top_srcdir)/libhypnos/ -I$(top_srcdir)/includes/'
+if test "$use_pch" == "yes"; then
+	PCHINCLUDES='-I$(top_builddir)/libhypnos/ -I$(top_builddir)/includes/'
+else
+	PCHINCLUDES=''
+fi
 
 TMPFLAGS="$WEFTS_CXXFLAGS -Wall"
 
@@ -23334,8 +23376,9 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 
 
-CFLAGS="$CFLAGS $INCLUDES $WORKING_CFLAGS $DEFDIRS"
-CXXFLAGS="$CXXFLAGS $INCLUDES $WORKING_CXXFLAGS $DEFDIRS"
+CPPFLAGS="$INCLUDES $CPPFLAGS $WEFTS_CXXFLAGS $MXML_CXXFLAGS $DEFDIRS $BINRELOC_CFLAGS -DHAVE_CONFIG_H "
+CFLAGS="$CFLAGS $WORKING_CFLAGS $PCHINCLUDES $CPPFLAGS"
+CXXFLAGS="$CXXFLAGS $WORKING_CXXFLAGS $PCHINCLUDES $CPPFLAGS"
 
 if test "x$is_icc" == "xyes"; then
 	CFLAGS="$CFLAGS -wd143 -wd177 -wd279 -wd383 -wd810 -wd981 "
@@ -23346,6 +23389,7 @@ if test "x$GCC" == "xyes"; then
 	CFLAGS="$CFLAGS -Wno-switch-enum "
 	CXXFLAGS="$CXXFLAGS -Wno-switch-enum -Wno-reorder "
 fi
+
 
 
 
@@ -23460,6 +23504,13 @@ if test -z "${BINRELOC_TRUE}" && test -z "${BINRELOC_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BINRELOC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BINRELOC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_PCH_TRUE}" && test -z "${HAVE_PCH_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_PCH\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_PCH\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -24084,6 +24135,8 @@ s,@BINRELOC_CFLAGS@,$BINRELOC_CFLAGS,;t t
 s,@BINRELOC_LIBS@,$BINRELOC_LIBS,;t t
 s,@BINRELOC_TRUE@,$BINRELOC_TRUE,;t t
 s,@BINRELOC_FALSE@,$BINRELOC_FALSE,;t t
+s,@HAVE_PCH_TRUE@,$HAVE_PCH_TRUE,;t t
+s,@HAVE_PCH_FALSE@,$HAVE_PCH_FALSE,;t t
 s,@WIN32_TRUE@,$WIN32_TRUE,;t t
 s,@WIN32_FALSE@,$WIN32_FALSE,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
