Made configure fail if wefts is not found.

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -463,7 +463,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP LN_S build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL DYNAMIC_LD_LIBS WEFTS_CONFIG WEFTS_CXXFLAGS WEFTS_LIBS BINRELOC_CFLAGS BINRELOC_LIBS BINRELOC_TRUE BINRELOC_FALSE HAVE_PCH_TRUE HAVE_PCH_FALSE WIN32_TRUE WIN32_FALSE LIBOBJS CPPLIB LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP LN_S build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL DYNAMIC_LD_LIBS BINRELOC_CFLAGS BINRELOC_LIBS BINRELOC_TRUE BINRELOC_FALSE HAVE_PCH_TRUE HAVE_PCH_FALSE WEFTS_CONFIG WEFTS_CXXFLAGS WEFTS_LIBS WIN32_TRUE WIN32_FALSE LIBOBJS CPPLIB LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1032,12 +1032,12 @@ Optional Features:
   --enable-fast-install[=PKGS]
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
-  --disable-weftstest       Do not try to compile and run a test Wefts++ program
   --enable-binreloc       compile with binary relocation support
                           (default=enable when available)
   --enable-binreloc-threads      compile binary relocation with threads support
 	                         (default=yes)
   --enable-pch            enables precompiled headers support
+  --disable-weftstest       Do not try to compile and run a test Wefts++ program
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -19645,210 +19645,6 @@ echo "$as_me: error: dynamic linker needed" >&2;}
 
 
 
-
-
-# Check whether --with-wefts-prefix or --without-wefts-prefix was given.
-if test "${with_wefts_prefix+set}" = set; then
-  withval="$with_wefts_prefix"
-  wefts_prefix="$withval"
-else
-  wefts_prefix=""
-fi;
-
-# Check whether --with-wefts-exec-prefix or --without-wefts-exec-prefix was given.
-if test "${with_wefts_exec_prefix+set}" = set; then
-  withval="$with_wefts_exec_prefix"
-  wefts_exec_prefix="$withval"
-else
-  wefts_exec_prefix=""
-fi;
-# Check whether --enable-weftstest or --disable-weftstest was given.
-if test "${enable_weftstest+set}" = set; then
-  enableval="$enable_weftstest"
-
-else
-  enable_weftstest=yes
-fi;
-
-  if test x$wefts_exec_prefix != x ; then
-     wefts_args="$wefts_args --exec-prefix=$wefts_exec_prefix"
-     if test x${WEFTS_CONFIG+set} != xset ; then
-        WEFTS_CONFIG=$wefts_exec_prefix/bin/wefts-conf
-     fi
-  fi
-  if test x$wefts_prefix != x ; then
-     wefts_args="$wefts_args --prefix=$wefts_prefix"
-     if test x${WEFTS_CONFIG+set} != xset ; then
-        WEFTS_CONFIG=$wefts_prefix/bin/wefts-conf
-     fi
-  fi
-
-  # Extract the first word of "wefts-conf", so it can be a program name with args.
-set dummy wefts-conf; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_path_WEFTS_CONFIG+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  case $WEFTS_CONFIG in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_WEFTS_CONFIG="$WEFTS_CONFIG" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-as_dummy="$prefix/bin:$PATH"
-for as_dir in $as_dummy
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_path_WEFTS_CONFIG="$as_dir/$ac_word$ac_exec_ext"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-  test -z "$ac_cv_path_WEFTS_CONFIG" && ac_cv_path_WEFTS_CONFIG="no"
-  ;;
-esac
-fi
-WEFTS_CONFIG=$ac_cv_path_WEFTS_CONFIG
-
-if test -n "$WEFTS_CONFIG"; then
-  echo "$as_me:$LINENO: result: $WEFTS_CONFIG" >&5
-echo "${ECHO_T}$WEFTS_CONFIG" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-  echo "$as_me:$LINENO: checking for Wefts++" >&5
-echo $ECHO_N "checking for Wefts++... $ECHO_C" >&6
-  no_wefts=""
-  if test "$WEFTS_CONFIG" = "no" ; then
-    no_wefts=yes
-  else
-    WEFTS_CXXFLAGS=`$WEFTS_CONFIG $weftsconf_args --cflags`
-    WEFTS_LIBS=`$WEFTS_CONFIG $weftsconf_args --libs`
-
-    if test "x$enable_weftstest" = "xyes" ; then
-      ac_save_CXXFLAGS="$CXXFLAGS"
-      ac_save_LIBS="$LIBS"
-      CXXFLAGS="$CXXFLAGS $WEFTS_CXXFLAGS"
-      LIBS="$LIBS $WEFTS_LIBS"
-
-    CXXFLAGS="$ac_save_CXXFLAGS"
-    LIBS="$ac_save_LIBS"
-    fi
-  fi
-
-  if test "x$no_wefts" = x ; then
-
-     echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-     :
-
-  else
-
-     echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-
-     if test "$WEFTS_CONFIG" = "no" ; then
-
-       echo "*** The wefts-conf script installed by Wefts++ could not be found"
-       echo "*** If Wefts++ was installed in PREFIX, make sure PREFIX/bin is in"
-       echo "*** your path, or set the WEFTS_CONFIG environment variable to the"
-       echo "*** full path to wefts-conf."
-
-     else
-       if test -f conf.weftstest ; then
-        :
-       else
-
-          echo "*** Could not run Wefts++ test program, checking why..."
-          CXXFLAGS="$CXXFLAGS $WEFTS_CXXFLAGS"
-          LIBS="$LIBS $WEFTS_LIBS"
-
-          echo $LIBS;
-
-          cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <wefts.h>
-int
-main ()
-{
- return 0;
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_cxx_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-
-          echo "*** The test program compiled, but did not run. This usually means"
-          echo "*** that the run-time linker is not finding Wefts++ or finding the wrong"
-          echo "*** version of Wefts++. If it is not finding Wefts++, you'll need to set your"
-          echo "*** LD_LIBRARY_PATH environment variable, or edit /etc/ld.so.conf to point"
-          echo "*** to the installed location  Also, make sure you have run ldconfig if that"
-          echo "*** is required on your system"
-	        echo "***"
-          echo "*** If you have an old version installed, it is best to remove it, although"
-          echo "*** you may also be able to get things to work by modifying LD_LIBRARY_PATH"
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
- echo "*** The test program failed to compile or link. See the file config.log for the"
-          echo "*** exact error that occured. This usually means Wefts++ was incorrectly installed"
-          echo "*** or that you have moved Wefts++ since it was installed. In the latter case, you"
-          echo "*** may want to edit the wefts-conf script: $WEFTS_CONFIG"
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-          CXXFLAGS="$ac_save_CXXFLAGS"
-          LIBS="$ac_save_LIBS"
-       fi
-     fi
-
-     WEFTS_CXXFLAGS=""
-     WEFTS_LIBS=""
-     :
-
-  fi
-
-
-
-
-  rm -f conf.weftstest
-
-
-
 	echo "$as_me:$LINENO: checking for Intel C++ Compiler" >&5
 echo $ECHO_N "checking for Intel C++ Compiler... $ECHO_C" >&6
 if test "${is_icc+set}" = set; then
@@ -20920,6 +20716,216 @@ fi
 
 
 
+
+
+
+
+# Check whether --with-wefts-prefix or --without-wefts-prefix was given.
+if test "${with_wefts_prefix+set}" = set; then
+  withval="$with_wefts_prefix"
+  wefts_prefix="$withval"
+else
+  wefts_prefix=""
+fi;
+
+# Check whether --with-wefts-exec-prefix or --without-wefts-exec-prefix was given.
+if test "${with_wefts_exec_prefix+set}" = set; then
+  withval="$with_wefts_exec_prefix"
+  wefts_exec_prefix="$withval"
+else
+  wefts_exec_prefix=""
+fi;
+# Check whether --enable-weftstest or --disable-weftstest was given.
+if test "${enable_weftstest+set}" = set; then
+  enableval="$enable_weftstest"
+
+else
+  enable_weftstest=yes
+fi;
+
+  if test x$wefts_exec_prefix != x ; then
+     wefts_args="$wefts_args --exec-prefix=$wefts_exec_prefix"
+     if test x${WEFTS_CONFIG+set} != xset ; then
+        WEFTS_CONFIG=$wefts_exec_prefix/bin/wefts-conf
+     fi
+  fi
+  if test x$wefts_prefix != x ; then
+     wefts_args="$wefts_args --prefix=$wefts_prefix"
+     if test x${WEFTS_CONFIG+set} != xset ; then
+        WEFTS_CONFIG=$wefts_prefix/bin/wefts-conf
+     fi
+  fi
+
+  # Extract the first word of "wefts-conf", so it can be a program name with args.
+set dummy wefts-conf; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_WEFTS_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $WEFTS_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_WEFTS_CONFIG="$WEFTS_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+as_dummy="$prefix/bin:$PATH"
+for as_dir in $as_dummy
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_WEFTS_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_WEFTS_CONFIG" && ac_cv_path_WEFTS_CONFIG="no"
+  ;;
+esac
+fi
+WEFTS_CONFIG=$ac_cv_path_WEFTS_CONFIG
+
+if test -n "$WEFTS_CONFIG"; then
+  echo "$as_me:$LINENO: result: $WEFTS_CONFIG" >&5
+echo "${ECHO_T}$WEFTS_CONFIG" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  echo "$as_me:$LINENO: checking for Wefts++" >&5
+echo $ECHO_N "checking for Wefts++... $ECHO_C" >&6
+  no_wefts=""
+  if test "$WEFTS_CONFIG" = "no" ; then
+    no_wefts=yes
+  else
+    WEFTS_CXXFLAGS=`$WEFTS_CONFIG $weftsconf_args --cflags`
+    WEFTS_LIBS=`$WEFTS_CONFIG $weftsconf_args --libs`
+
+    if test "x$enable_weftstest" = "xyes" ; then
+      ac_save_CXXFLAGS="$CXXFLAGS"
+      ac_save_LIBS="$LIBS"
+      CXXFLAGS="$CXXFLAGS $WEFTS_CXXFLAGS"
+      LIBS="$LIBS $WEFTS_LIBS"
+
+    CXXFLAGS="$ac_save_CXXFLAGS"
+    LIBS="$ac_save_LIBS"
+    fi
+  fi
+
+  if test "x$no_wefts" = x ; then
+
+     echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+     :
+
+  else
+
+     echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
+     if test "$WEFTS_CONFIG" = "no" ; then
+
+       echo "*** The wefts-conf script installed by Wefts++ could not be found"
+       echo "*** If Wefts++ was installed in PREFIX, make sure PREFIX/bin is in"
+       echo "*** your path, or set the WEFTS_CONFIG environment variable to the"
+       echo "*** full path to wefts-conf."
+
+     else
+       if test -f conf.weftstest ; then
+        :
+       else
+
+          echo "*** Could not run Wefts++ test program, checking why..."
+          CXXFLAGS="$CXXFLAGS $WEFTS_CXXFLAGS"
+          LIBS="$LIBS $WEFTS_LIBS"
+
+          echo $LIBS;
+
+          cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <wefts.h>
+int
+main ()
+{
+ return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+          echo "*** The test program compiled, but did not run. This usually means"
+          echo "*** that the run-time linker is not finding Wefts++ or finding the wrong"
+          echo "*** version of Wefts++. If it is not finding Wefts++, you'll need to set your"
+          echo "*** LD_LIBRARY_PATH environment variable, or edit /etc/ld.so.conf to point"
+          echo "*** to the installed location  Also, make sure you have run ldconfig if that"
+          echo "*** is required on your system"
+	        echo "***"
+          echo "*** If you have an old version installed, it is best to remove it, although"
+          echo "*** you may also be able to get things to work by modifying LD_LIBRARY_PATH"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ echo "*** The test program failed to compile or link. See the file config.log for the"
+          echo "*** exact error that occured. This usually means Wefts++ was incorrectly installed"
+          echo "*** or that you have moved Wefts++ since it was installed. In the latter case, you"
+          echo "*** may want to edit the wefts-conf script: $WEFTS_CONFIG"
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+          CXXFLAGS="$ac_save_CXXFLAGS"
+          LIBS="$ac_save_LIBS"
+       fi
+     fi
+
+     WEFTS_CXXFLAGS=""
+     WEFTS_LIBS=""
+     :
+
+  fi
+
+
+
+
+  rm -f conf.weftstest
+
+
+if test "$WEFTS_LIBS" = ""; then
+	{ { echo "$as_me:$LINENO: error: Unable to find Wefts++ library. Error on configure." >&5
+echo "$as_me: error: Unable to find Wefts++ library. Error on configure." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 
 
@@ -25007,15 +25013,15 @@ s,@FFLAGS@,$FFLAGS,;t t
 s,@ac_ct_F77@,$ac_ct_F77,;t t
 s,@LIBTOOL@,$LIBTOOL,;t t
 s,@DYNAMIC_LD_LIBS@,$DYNAMIC_LD_LIBS,;t t
-s,@WEFTS_CONFIG@,$WEFTS_CONFIG,;t t
-s,@WEFTS_CXXFLAGS@,$WEFTS_CXXFLAGS,;t t
-s,@WEFTS_LIBS@,$WEFTS_LIBS,;t t
 s,@BINRELOC_CFLAGS@,$BINRELOC_CFLAGS,;t t
 s,@BINRELOC_LIBS@,$BINRELOC_LIBS,;t t
 s,@BINRELOC_TRUE@,$BINRELOC_TRUE,;t t
 s,@BINRELOC_FALSE@,$BINRELOC_FALSE,;t t
 s,@HAVE_PCH_TRUE@,$HAVE_PCH_TRUE,;t t
 s,@HAVE_PCH_FALSE@,$HAVE_PCH_FALSE,;t t
+s,@WEFTS_CONFIG@,$WEFTS_CONFIG,;t t
+s,@WEFTS_CXXFLAGS@,$WEFTS_CXXFLAGS,;t t
+s,@WEFTS_LIBS@,$WEFTS_LIBS,;t t
 s,@WIN32_TRUE@,$WIN32_TRUE,;t t
 s,@WIN32_FALSE@,$WIN32_FALSE,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
