Added Makefiles to libhypnos headers (which should be installed in the include dir). Conditionally compile only if win32 the win32registry and ntservice (configure check). Autogened to apply the changes.

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -463,7 +463,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE CC CFLAGS ac_ct_CC CCDEPMODE CPP LN_S build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL DYNAMIC_LD_LIBS WEFTS_CONFIG WEFTS_CXXFLAGS WEFTS_LIBS BINRELOC_CFLAGS BINRELOC_LIBS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE CC CFLAGS ac_ct_CC CCDEPMODE CPP LN_S build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL DYNAMIC_LD_LIBS WEFTS_CONFIG WEFTS_CXXFLAGS WEFTS_LIBS BINRELOC_CFLAGS BINRELOC_LIBS WIN32_TRUE WIN32_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -21188,6 +21188,17 @@ done
 
 fi
 
+
+
+if test x$is_win = "xyes"; then
+  WIN32_TRUE=
+  WIN32_FALSE='#'
+else
+  WIN32_TRUE='#'
+  WIN32_FALSE=
+fi
+
+
 # Checks for typedefs, structures, and compiler characteristics.
 echo "$as_me:$LINENO: checking for stdbool.h that conforms to C99" >&5
 echo $ECHO_N "checking for stdbool.h that conforms to C99... $ECHO_C" >&6
@@ -22980,7 +22991,7 @@ LDFLAGS="$LDFLAGS"
 
 
 
-                                                                                                                                                                          ac_config_files="$ac_config_files Makefile libhypnos/Makefile libhypnos/muls/Makefile utils/Makefile utils/clilist/Makefile src/Makefile src/archetypes/Makefile src/archs/Makefile src/backend/Makefile src/encryption/Makefile src/extras/Makefile src/networking/Makefile src/objects/Makefile src/objects/cchar/Makefile src/objects/citem/Makefile src/objects/cnpc/Makefile src/skills/Makefile"
+                                                                                                                                                                                              ac_config_files="$ac_config_files Makefile libhypnos/Makefile libhypnos/muls/Makefile libhypnos/libhypnos/Makefile libhypnos/libhypnos/muls/Makefile utils/Makefile utils/clilist/Makefile src/Makefile src/archetypes/Makefile src/archs/Makefile src/backend/Makefile src/encryption/Makefile src/extras/Makefile src/networking/Makefile src/objects/Makefile src/objects/cchar/Makefile src/objects/citem/Makefile src/objects/cnpc/Makefile src/skills/Makefile"
 
 
 cat >confcache <<\_ACEOF
@@ -23078,6 +23089,13 @@ if test -z "${AMDEP_TRUE}" && test -z "${AMDEP_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"AMDEP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"AMDEP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${WIN32_TRUE}" && test -z "${WIN32_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"WIN32\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"WIN32\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -23528,6 +23546,8 @@ do
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "libhypnos/Makefile" ) CONFIG_FILES="$CONFIG_FILES libhypnos/Makefile" ;;
   "libhypnos/muls/Makefile" ) CONFIG_FILES="$CONFIG_FILES libhypnos/muls/Makefile" ;;
+  "libhypnos/libhypnos/Makefile" ) CONFIG_FILES="$CONFIG_FILES libhypnos/libhypnos/Makefile" ;;
+  "libhypnos/libhypnos/muls/Makefile" ) CONFIG_FILES="$CONFIG_FILES libhypnos/libhypnos/muls/Makefile" ;;
   "utils/Makefile" ) CONFIG_FILES="$CONFIG_FILES utils/Makefile" ;;
   "utils/clilist/Makefile" ) CONFIG_FILES="$CONFIG_FILES utils/clilist/Makefile" ;;
   "src/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
@@ -23691,6 +23711,8 @@ s,@WEFTS_CXXFLAGS@,$WEFTS_CXXFLAGS,;t t
 s,@WEFTS_LIBS@,$WEFTS_LIBS,;t t
 s,@BINRELOC_CFLAGS@,$BINRELOC_CFLAGS,;t t
 s,@BINRELOC_LIBS@,$BINRELOC_LIBS,;t t
+s,@WIN32_TRUE@,$WIN32_TRUE,;t t
+s,@WIN32_FALSE@,$WIN32_FALSE,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
