Added m4 script to check for Wefts (took from ZThead). Changed autogen.sh to *not* run ./configure. Changed configure.in to check for Wefts. Regenerated configure stuff.

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -463,7 +463,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS ac_ct_CC CCDEPMODE EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL DYNAMIC_LD_LIBS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS ac_ct_CC CCDEPMODE EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL DYNAMIC_LD_LIBS WEFTS_CONFIG WEFTS_CXXFLAGS WEFTS_LIBS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1032,6 +1032,7 @@ Optional Features:
   --enable-fast-install[=PKGS]
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
+  --disable-weftstest       Do not try to compile and run a test Wefts++ program
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -1041,6 +1042,8 @@ Optional Packages:
                           both]
   --with-tags[=TAGS]
                           include additional configurations [automatic]
+  --with-wefts-prefix=PFX   Prefix where Wefts++ is installed (optional)
+  --with-wefts-exec-prefix=PFX Exec prefix where Wefts++ is installed (optional)
 
 Some influential environment variables:
   CXX         C++ compiler command
@@ -3994,7 +3997,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3997 "configure"' > conftest.$ac_ext
+  echo '#line 4000 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5120,7 +5123,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5123:" \
+echo "$as_me:5126:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6154,11 +6157,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6157: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6160: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6161: \$? = $ac_status" >&5
+   echo "$as_me:6164: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6387,11 +6390,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6390: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6393: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6394: \$? = $ac_status" >&5
+   echo "$as_me:6397: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6447,11 +6450,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6450: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6453: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6454: \$? = $ac_status" >&5
+   echo "$as_me:6457: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -7826,7 +7829,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*)
-    echo '#line 7829 "configure"' > conftest.$ac_ext
+    echo '#line 7832 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8686,7 +8689,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8689 "configure"
+#line 8692 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8784,7 +8787,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8787 "configure"
+#line 8790 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10963,11 +10966,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10966: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10969: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10970: \$? = $ac_status" >&5
+   echo "$as_me:10973: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -11023,11 +11026,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11026: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11029: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11030: \$? = $ac_status" >&5
+   echo "$as_me:11033: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11579,7 +11582,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*)
-    echo '#line 11582 "configure"' > conftest.$ac_ext
+    echo '#line 11585 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -12439,7 +12442,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12442 "configure"
+#line 12445 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12537,7 +12540,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12540 "configure"
+#line 12543 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13364,11 +13367,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13367: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13370: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13371: \$? = $ac_status" >&5
+   echo "$as_me:13374: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -13424,11 +13427,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13427: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13430: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13431: \$? = $ac_status" >&5
+   echo "$as_me:13434: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14783,7 +14786,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*)
-    echo '#line 14786 "configure"' > conftest.$ac_ext
+    echo '#line 14789 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -15513,11 +15516,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15516: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15519: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15520: \$? = $ac_status" >&5
+   echo "$as_me:15523: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15746,11 +15749,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15749: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15752: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15753: \$? = $ac_status" >&5
+   echo "$as_me:15756: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15806,11 +15809,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15809: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15812: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15813: \$? = $ac_status" >&5
+   echo "$as_me:15816: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17185,7 +17188,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*)
-    echo '#line 17188 "configure"' > conftest.$ac_ext
+    echo '#line 17191 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -18045,7 +18048,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18048 "configure"
+#line 18051 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18143,7 +18146,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18146 "configure"
+#line 18149 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19176,11 +19179,6 @@ LIBTOOL='$(SHELL) $(top_builddir)/libtool'
 
 
 
-INCLUDES='-I$(top_srcdir)/libhypnos/ -I$(top_srcdir)/includes/'
-CXXFLAGS="$CXXFLAGS $INCLUDES -Wall -Wno-reorder -Wno-switch-enum"
-
-
-
 
   echo "$as_me:$LINENO: checking for dlopen in -lc" >&5
 echo $ECHO_N "checking for dlopen in -lc... $ECHO_C" >&6
@@ -19404,6 +19402,216 @@ echo "$as_me: error: dynamic linker needed" >&2;}
    { (exit 1); exit 1; }; }
   fi
 
+
+
+
+
+
+
+# Check whether --with-wefts-prefix or --without-wefts-prefix was given.
+if test "${with_wefts_prefix+set}" = set; then
+  withval="$with_wefts_prefix"
+  wefts_prefix="$withval"
+else
+  wefts_prefix=""
+fi;
+
+# Check whether --with-wefts-exec-prefix or --without-wefts-exec-prefix was given.
+if test "${with_wefts_exec_prefix+set}" = set; then
+  withval="$with_wefts_exec_prefix"
+  wefts_exec_prefix="$withval"
+else
+  wefts_exec_prefix=""
+fi;
+# Check whether --enable-weftstest or --disable-weftstest was given.
+if test "${enable_weftstest+set}" = set; then
+  enableval="$enable_weftstest"
+
+else
+  enable_weftstest=yes
+fi;
+
+  if test x$wefts_exec_prefix != x ; then
+     wefts_args="$wefts_args --exec-prefix=$wefts_exec_prefix"
+     if test x${WEFTS_CONFIG+set} != xset ; then
+        WEFTS_CONFIG=$wefts_exec_prefix/bin/wefts-conf
+     fi
+  fi
+  if test x$wefts_prefix != x ; then
+     wefts_args="$wefts_args --prefix=$wefts_prefix"
+     if test x${WEFTS_CONFIG+set} != xset ; then
+        WEFTS_CONFIG=$wefts_prefix/bin/wefts-conf
+     fi
+  fi
+
+  # Extract the first word of "wefts-conf", so it can be a program name with args.
+set dummy wefts-conf; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_WEFTS_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $WEFTS_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_WEFTS_CONFIG="$WEFTS_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_WEFTS_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_WEFTS_CONFIG" && ac_cv_path_WEFTS_CONFIG="no"
+  ;;
+esac
+fi
+WEFTS_CONFIG=$ac_cv_path_WEFTS_CONFIG
+
+if test -n "$WEFTS_CONFIG"; then
+  echo "$as_me:$LINENO: result: $WEFTS_CONFIG" >&5
+echo "${ECHO_T}$WEFTS_CONFIG" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  echo "$as_me:$LINENO: checking for Wefts++" >&5
+echo $ECHO_N "checking for Wefts++... $ECHO_C" >&6
+  no_wefts=""
+  if test "$WEFTS_CONFIG" = "no" ; then
+    no_wefts=yes
+  else
+    WEFTS_CXXFLAGS=`$WEFTS_CONFIG $weftsconf_args --cflags`
+    WEFTS_LIBS=`$WEFTS_CONFIG $weftsconf_args --libs`
+
+    if test "x$enable_weftstest" = "xyes" ; then
+      ac_save_CXXFLAGS="$CXXFLAGS"
+      ac_save_LIBS="$LIBS"
+      CXXFLAGS="$CXXFLAGS $WEFTS_CXXFLAGS"
+      LIBS="$LIBS $WEFTS_LIBS"
+
+    CXXFLAGS="$ac_save_CXXFLAGS"
+    LIBS="$ac_save_LIBS"
+    fi
+  fi
+
+  if test "x$no_wefts" = x ; then
+
+     echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+     :
+
+  else
+
+     echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
+     if test "$WEFTS_CONFIG" = "no" ; then
+
+       echo "*** The wefts-conf script installed by Wefts++ could not be found"
+       echo "*** If Wefts++ was installed in PREFIX, make sure PREFIX/bin is in"
+       echo "*** your path, or set the WEFTS_CONFIG environment variable to the"
+       echo "*** full path to wefts-conf."
+
+     else
+       if test -f conf.weftstest ; then
+        :
+       else
+
+          echo "*** Could not run Wefts++ test program, checking why..."
+          CXXFLAGS="$CXXFLAGS $WEFTS_CXXFLAGS"
+          LIBS="$LIBS $WEFTS_LIBS"
+
+          echo $LIBS;
+
+          cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <wefts.h>
+int
+main ()
+{
+ return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+          echo "*** The test program compiled, but did not run. This usually means"
+          echo "*** that the run-time linker is not finding Wefts++ or finding the wrong"
+          echo "*** version of Wefts++. If it is not finding Wefts++, you'll need to set your"
+          echo "*** LD_LIBRARY_PATH environment variable, or edit /etc/ld.so.conf to point"
+          echo "*** to the installed location  Also, make sure you have run ldconfig if that"
+          echo "*** is required on your system"
+	        echo "***"
+          echo "*** If you have an old version installed, it is best to remove it, although"
+          echo "*** you may also be able to get things to work by modifying LD_LIBRARY_PATH"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ echo "*** The test program failed to compile or link. See the file config.log for the"
+          echo "*** exact error that occured. This usually means Wefts++ was incorrectly installed"
+          echo "*** or that you have moved Wefts++ since it was installed. In the latter case, you"
+          echo "*** may want to edit the wefts-conf script: $WEFTS_CONFIG"
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+          CXXFLAGS="$ac_save_CXXFLAGS"
+          LIBS="$ac_save_LIBS"
+       fi
+     fi
+
+     WEFTS_CXXFLAGS=""
+     WEFTS_LIBS=""
+     :
+
+  fi
+
+
+
+
+  rm -f conf.weftstest
+
+
+
+INCLUDES='-I$(top_srcdir)/libhypnos/ -I$(top_srcdir)/includes/'
+CXXFLAGS="$CXXFLAGS $INCLUDES -Wall -Wno-reorder -Wno-switch-enum $WEFTS_CXXFLAGS"
+LDFLAGS="$LDFLAGS $WEFTS_LIBS"
 
 
 
@@ -20110,6 +20318,9 @@ s,@FFLAGS@,$FFLAGS,;t t
 s,@ac_ct_F77@,$ac_ct_F77,;t t
 s,@LIBTOOL@,$LIBTOOL,;t t
 s,@DYNAMIC_LD_LIBS@,$DYNAMIC_LD_LIBS,;t t
+s,@WEFTS_CONFIG@,$WEFTS_CONFIG,;t t
+s,@WEFTS_CXXFLAGS@,$WEFTS_CXXFLAGS,;t t
+s,@WEFTS_LIBS@,$WEFTS_LIBS,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
